### ISSUE TITLE
Doesn't work in IntelliJ

### ISSUE THREAD

**Issue by dxxvi** [alonsodomin/sbt-spark#5]
Everything works fine in sbt, but IntelliJ keeps saying libraries missing when the app is run from the IDE. Is there any way to configure IntelliJ to make everything work?

**Comment by alonsodomin** [comment]
Do you mind explaining a bit more what type of error is what you are getting in your IDE? ... or put an screenshot of it?

I seldom use IntelliJ but from what I can imagine, if your problem is when running the application (what you would do from the terminal with an `sbt run`), then most likely it could fail if IntelliJ is not adding the Spark dependencies in the running classpath (Spark dependencies need to be in the `provided` scope). If this is the case I would suggest running it using the SBT Shell feature in IntelliJ and see what happens.
